#!/usr/bin/env python3
"""Extract WeirdLoot named-item lines from the guild loot sheet.

The sheet tab is a pair of side-by-side blocks (25-man, 10-man), each six columns wide:
item name, spacer, then three priority columns (tier 1, 2, 3), then a spare. A ">" inside a cell is
a tier boundary just like a column boundary. Tokens within a tier
are slash separated and are player names or the addon's LC / rest keywords; the sheet decides
which items end in LC, nothing is appended here. Rows that are section headers (boss, Hard Mode,
Trash, Tier Tokens, class groups) carry no tokens and are skipped. The "BIG ITEMS" block to the
right is derived from the boss blocks and is ignored. Output is one WeirdLoot named-items line per
item that has at least one token:

    Item Name, tier1a / tier1b > tier2a > LC

Usage:
    tools/sheet_named_items.py [--gid GID ...] [--sheet ID] [--csv FILE] [--txt PATH] [--lua [PATH]]

Reads the public CSV export (no auth). --csv reads a saved export instead of downloading. With no
output flag the lines go to stdout. --txt writes them to a gitignored paste file (named_items.txt
in the addon root, or a given path) for the addon's Import Named Items window. --lua rewrites the defaultNamedItemsText block in Data/LootPrios.lua
(the shipped default every client loads) in place; the block is regenerated wholesale, so every
tab that should ship must be given as a --gid. Both may be combined.
Cells that are neither names nor keywords (class text like "prot pala/prot war") are reported on
stderr and left out of the line: the named list only takes names; class rules belong in the spec list.
"""
import argparse, csv, io, os, re, sys, urllib.request

SHEET = "1p_MZ7c8IU1D2V2lp6Sovbif0KOMxL0px2pT8VhTwsqo"
GID = "1419766178"        # the "Ulduar_Untrimmed" tab
BLOCK = 6                  # columns per size block
TIER_COLS = (2, 3, 4)      # the three priority columns inside a block, in order
NAME = re.compile(r"^[A-Za-z]{2,12}$")   # a WoW character name; anything else is class text or a note
KEYWORDS = {"lc", "rest"}                # named-list tokens the addon parser understands besides names

def is_token(t):
    return t.lower() in KEYWORDS or bool(NAME.match(t))

def fetch(sheet, gid):
    url = f"https://docs.google.com/spreadsheets/d/{sheet}/export?format=csv&gid={gid}"
    return urllib.request.urlopen(url).read().decode("utf-8")

def block_lines(rows, base, warn):
    out = []
    for r in rows:
        cells = [(r[base + i] if base + i < len(r) else "").strip() for i in range(BLOCK)]
        item = cells[0]
        if not item:
            continue
        tiers = []
        for c in TIER_COLS:
            raw = cells[c]
            if not raw:
                continue
            # ">" is a tier boundary wherever it appears, including inside a single cell: the sheet
            # writes a run of tiers in one column when it runs out of columns.
            for part in raw.split(">"):
                names = [n.strip() for n in part.split("/") if n.strip()]
                good = [n for n in names if is_token(n)]
                bad = [n for n in names if not is_token(n)]
                if bad:
                    warn(f"{item}: skipped non-name cell text {bad!r}")
                if good:
                    tiers.append(" / ".join(good))
        if not tiers:
            continue
        out.append(f"{item}, {' > '.join(tiers)}")
    return out

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
LUA_PATH = os.path.join(ROOT, "Data", "LootPrios.lua")
TXT_PATH = os.path.join(ROOT, "named_items.txt")   # gitignored paste file
LUA_BLOCK = re.compile(r'addon\.defaultNamedItemsText = table\.concat\(\{\n.*?\n\}, "\\n"\)', re.S)

def write_lua(path, lines, source):
    src = open(path, encoding="utf-8").read()
    if not LUA_BLOCK.search(src):
        sys.exit(f"{path}: defaultNamedItemsText block not found")
    body = "\n".join('    "%s",' % l.replace("\\", "\\\\").replace('"', '\\"') for l in lines)
    block = ('-- Generated by tools/sheet_named_items.py from the loot sheet (%s); rerun it rather\n'
             '-- than editing these lines.\n'
             'addon.defaultNamedItemsText = table.concat({\n%s\n}, "\\n")') % (source, body)
    # Drop a previous generated header so reruns do not stack them.
    src = re.sub(r'-- Generated by tools/sheet_named_items\.py[^\n]*\n(-- [^\n]*\n)*', '', src)
    open(path, "w", encoding="utf-8").write(LUA_BLOCK.sub(lambda _: block, src, count=1))

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sheet", default=SHEET)
    ap.add_argument("--gid", action="append", help="tab gid; repeatable, default the ulduar tab")
    ap.add_argument("--csv", help="read this saved CSV export instead of downloading")
    ap.add_argument("--txt", nargs="?", const=TXT_PATH, help="write the paste file for Import Named Items (default named_items.txt in the addon root)")
    ap.add_argument("--lua", nargs="?", const=LUA_PATH, help="rewrite the shipped default block (default Data/LootPrios.lua)")
    args = ap.parse_args()
    gids = args.gid or [GID]
    warn = lambda m: print("warning: " + m, file=sys.stderr)

    seen = {}
    lines = []
    sources = [args.csv] if args.csv else [f"gid {g}" for g in gids]
    for text in ([open(args.csv, encoding="utf-8").read()] if args.csv
                 else [fetch(args.sheet, g) for g in gids]):
        rows = list(csv.reader(io.StringIO(text)))
        for base in (0, BLOCK):       # 25-man block, then 10-man block
            for line in block_lines(rows, base, warn):
                key = line.split(",", 1)[0].lower()
                if key in seen:
                    # The addon keys rules by item NAME, so a repeat (same item under two bosses, a
                    # 10/25 pair that shares a name, or the same item on two tabs) can only carry one
                    # rule. First occurrence wins; a conflicting repeat is for the sheet to resolve.
                    if seen[key] != line:
                        warn(f"conflicting repeat kept first: {seen[key]!r} vs {line!r}")
                    continue
                seen[key] = line
                lines.append(line)

    if args.txt:
        open(args.txt, "w", encoding="utf-8").write("\n".join(lines) + "\n")
        print(f"{len(lines)} lines -> {args.txt}", file=sys.stderr)
    if args.lua:
        write_lua(args.lua, lines, ", ".join(sources))
        print(f"{len(lines)} lines -> {args.lua}", file=sys.stderr)
    if not args.txt and not args.lua:
        print("\n".join(lines))

if __name__ == "__main__":
    main()
